// Serves the render directory as a downloadable gallery over HTTP.
// Usage: node ui-mockups/serve.js [port]
//   port defaults to 8742; bind 0.0.0.0 for the Arena live preview.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PORT = Number(process.argv[2] || 8742);

const screensDir = path.join(ROOT, 'screenshots');
const mockDir = path.join(ROOT, 'ui-mockups');

function listPngs(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.png')).sort();
}

function html() {
  const real = listPngs(screensDir).map((f) => `/screenshots/${f}`);
  const mock = listPngs(mockDir).map((f) => `/mockups/${f}`);
  const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const gallery = (title, items, note) => `
    <h2>${title}</h2>
    <p style="color:#888">${note}</p>
    ${
      items.length
        ? '<div style="display:flex;flex-wrap:wrap;gap:16px">' +
          items
            .map(
              (u) =>
                `<figure style="margin:0"><a href="${u}" download><img src="${u}" style="height:220px;border:1px solid #333;border-radius:6px" /></a><figcaption style="color:#aaa;font-size:12px;margin-top:4px">${esc(u.split('/').pop())} — <a href="${u}" download style="color:#e50914">download</a></figcaption></figure>`,
            )
            .join('') +
          '</div>'
        : '<p style="color:#666">None generated yet.</p>'
    }`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>Hirena UI renders</title>
<style>body{background:#0b0b0b;color:#eee;font-family:system-ui,sans-serif;margin:0;padding:32px;max-width:1200px}h1{font-weight:900;letter-spacing:1px}h1 span{color:#e50914}code{background:#1c1c1c;padding:2px 6px;border-radius:4px;color:#7fd7ff}a{color:#e50914}</style></head><body>
<h1>HIRENA <span>UI renders</span></h1>
${gallery(
  'Real Flutter renders',
  real,
  'Generated by Flutter\'s own engine via <code>flutter test test/screenshots/screenshots_test.dart</code> (or the CI "Render UI screenshots" job artifact).',
)}
${gallery(
  'Static mockups',
  mock,
  'Hand-drawn reference mockups (NOT Flutter output) — for quick preview only.',
)}
<p style="color:#666;margin-top:32px">How to get real renders: run <code>flutter test test/screenshots/screenshots_test.dart</code> on your machine, or enable the committed <code>.github/workflows/ci.yml</code> to upload them as a CI artifact.</p>
</body></html>`;
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://x');
  if (url.pathname === '/' || url.pathname === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(html());
    return;
  }
  let file = null;
  if (url.pathname.startsWith('/screenshots/')) {
    file = path.join(screensDir, path.basename(url.pathname));
  } else if (url.pathname.startsWith('/mockups/')) {
    file = path.join(mockDir, path.basename(url.pathname));
  }
  if (file && fs.existsSync(file) && file.endsWith('.png')) {
    res.writeHead(200, { 'Content-Type': 'image/png' });
    fs.createReadStream(file).pipe(res);
    return;
  }
  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('not found');
});

server.listen(PORT, '0.0.0.0', () => {
  console.log('Render gallery listening on http://0.0.0.0:' + PORT);
});
